export const regimenFiscal: Record<string, string> = {
  '601': 'General de Ley Personas Morales',
  '603': 'Personas Morales con Fines no Lucrativos',
  '605': 'Sueldos y Salarios e Ingresos Asimilados a Salarios',
  '606': 'Arrendamiento',
  '607': 'Régimen de Enajenación o Adquisición de Bienes',
  '608': 'Demás ingresos',
  '610': 'Residentes en el Extranjero sin Establecimiento Permanente en México',
  '611': 'Ingresos por Dividendos (socios y accionistas)',
  '612': 'Personas Físicas con Actividades Empresariales y Profesionales',
  '614': 'Ingresos por intereses',
  '615': 'Régimen de los ingresos por obtención de premios',
  '616': 'Sin obligaciones fiscales',
  '620': 'Sociedades Cooperativas de Producción que optan por diferir sus ingresos',
  '621': 'Incorporación Fiscal',
  '622': 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras',
  '623': 'Opcional para Grupos de Sociedades',
  '624': 'Coordinados',
  '625': 'Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas',
  '626': 'Régimen Simplificado de Confianza'
}

export const usoCFDI: Record<string, string> = {
  'G01': 'Adquisición de mercancias',
  'G02': 'Devoluciones, descuentos o bonificaciones',
  'G03': 'Gastos en general',
  'I01': 'Construcciones',
  'I02': 'Mobilario y equipo de oficina por inversiones',
  'I03': 'Equipo de transporte',
  'I04': 'Equipo de computo y accesorios',
  'I05': 'Dados, troqueles, moldes, matrices y herramental',
  'I06': 'Comunicaciones telefónicas',
  'I07': 'Comunicaciones satelitales',
  'I08': 'Otra maquinaria y equipo',
  'D01': 'Honorarios médicos, dentales y gastos hospitalarios',
  'D02': 'Gastos médicos por incapacidad o discapacidad',
  'D03': 'Gastos funerales',
  'D04': 'Donativos',
  'D05': 'Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)',
  'D06': 'Aportaciones voluntarias al SAR',
  'D07': 'Primas por seguros de gastos médicos',
  'D08': 'Gastos de transportación escolar obligatoria',
  'D09': 'Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones',
  'D10': 'Pagos por servicios educativos (colegiaturas)',
  'P01': 'Por definir',
  'S01': 'Sin efectos fiscales',
  'CP01': 'Pagos',
  'CN01': 'Nómina'
}

export const formaPago: Record<string, string> = {
  '01': 'Efectivo',
  '02': 'Cheque nominativo',
  '03': 'Transferencia electrónica de fondos',
  '04': 'Tarjeta de crédito',
  '05': 'Monedero electrónico',
  '06': 'Dinero electrónico',
  '08': 'Vales de despensa',
  '12': 'Dación en pago',
  '13': 'Pago por subrogación',
  '14': 'Pago por consignación',
  '15': 'Condonación',
  '17': 'Compensación',
  '23': 'Novación',
  '24': 'Confusión',
  '25': 'Remisión de deuda',
  '26': 'Prescripción o caducidad',
  '27': 'A satisfacción del acreedor',
  '28': 'Tarjeta de débito',
  '29': 'Tarjeta de servicios',
  '30': 'Aplicación de anticipos',
  '31': 'Intermediario pagos',
  '99': 'Por definir'
}

export const metodoPago: Record<string, string> = {
  'PUE': 'Pago en una sola exhibición',
  'PPD': 'Pago en parcialidades o diferido'
}

export const impuesto: Record<string, string> = {
  '001': 'ISR',
  '002': 'IVA',
  '003': 'IEPS'
}

export const tipoPercepcion: Record<string, string> = {
  '001': 'Sueldos, Salarios Rayas y Jornales',
  '002': 'Gratificación Anual (Aguinaldo)',
  '003': 'Participación de los Trabajadores en las Utilidades PTU',
  '004': 'Reembolso de Gastos Médicos Dentales y Hospitalarios',
  '005': 'Fondo de Ahorro',
  '006': 'Caja de ahorro',
  '009': 'Contribuciones a Cargo del Trabajador Pagadas por el Patrón',
  '010': 'Premios por Puntualidad',
  '011': 'Prima de Seguro de vida',
  '012': 'Seguro de Gastos Médicos Mayores',
  '013': 'Cuotas Sindicales Pagadas por el Patrón',
  '014': 'Subsidios por incapacidad',
  '015': 'Becas para trabajadores y/o hijos',
  '019': 'Horas extra',
  '020': 'Prima dominical',
  '021': 'Prima Vacacional',
  '022': 'Prima por antigüedad',
  '023': 'Pagos por separación',
  '024': 'Seguro de retiro',
  '025': 'Indemnizaciones',
  '026': 'Reembolso por funeral',
  '027': 'Cuotas de seguridad social pagadas por el patrón',
  '028': 'Comisiones',
  '029': 'Vales de despensa',
  '030': 'Vales de restaurante',
  '031': 'Vales de gasolina',
  '032': 'Vales de ropa',
  '033': 'Ayuda para renta',
  '034': 'Ayuda para artículos escolares',
  '035': 'Ayuda para anteojos',
  '036': 'Ayuda para transporte',
  '037': 'Ayuda para gastos de funeral',
  '038': 'Otros ingresos por salarios',
  '039': 'Jubilaciones, pensiones o haberes de retiro',
  '044': 'Jubilaciones, pensiones o haberes de retiro en parcialidades',
  '045': 'Ingresos en acciones o títulos valor que representan bienes',
  '046': 'Ingresos asimilados a salarios',
  '047': 'Alimentación diferentes a los establecidos en el Art 94 último párrafo LISR',
  '048': 'Habitación',
  '049': 'Premios por asistencia',
  '050': 'Viáticos',
  '051': 'Pagos por gratificaciones, primas, compensaciones, recompensas u otros a extrabajadores derivados de jubilación en parcialidades'
}

export const tipoDeduccion: Record<string, string> = {
  '001': 'Seguridad social',
  '002': 'ISR',
  '003': 'Aportaciones a retiro, cesantía en edad avanzada y vejez',
  '004': 'Otros',
  '005': 'Aportaciones a Fondo de vivienda',
  '006': 'Descuento por incapacidad',
  '007': 'Pensión alimenticia',
  '008': 'Renta',
  '009': 'Préstamos provenientes del Fondo Nacional de la Vivienda para los Trabajadores',
  '010': 'Pago por crédito de vivienda',
  '011': 'Pago de abonos INFONACOT',
  '012': 'Anticipo de salarios',
  '013': 'Pagos hechos con exceso al trabajador',
  '014': 'Errores',
  '015': 'Pérdidas',
  '016': 'Averías',
  '017': 'Adquisición de artículos producidos por la empresa o establecimiento',
  '018': 'Cuotas para la constitución y fomento de sociedades cooperativas y de cajas de ahorro',
  '019': 'Cuotas sindicales',
  '020': 'Ausencias (Ausentismo)',
  '021': 'Cuotas obrero patronales'
}

export const cat = (catalogo: Record<string, string>, clave: string) =>
  catalogo[clave] ? `${clave} - ${catalogo[clave]}` : clave